server:
  port: 8081


spring:
  datasource:
    url: jdbc:mariadb://cambak.cp5koktxnub1.ap-northeast-2.rds.amazonaws.com:3306/cambak?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: Goloonshot1!
    driver-class-name: org.mariadb.jdbc.Driver

# ===============================
# = JPA
# ===============================
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect //DDL Issue 발생
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# ===============================
# = Jwt
# ===============================
jwt:
  secret:
    key: cambakSecretKey
  refresh:
    key: cambakRefreshKey