server:
  port: 8081


spring:
  datasource:
    url: jdbc:mariadb://cambak.cp5koktxnub1.ap-northeast-2.rds.amazonaws.com:3306/cambak?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: Goloonshot1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update